# Generated by Django 5.1.6 on 2026-09-23 15:42

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assessed_on', models.DateField(db_index=True, help_text='The date this refers to, not the date it was typed in.', verbose_name='date')),
                ('cadence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='daily', max_length=10, verbose_name='cadence')),
                ('note', models.TextField(blank=True, help_text='What happened in this period. Explains the numbers later.', verbose_name='note')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='workspaces.workspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'assessment',
                'verbose_name_plural': 'assessments',
                'ordering': ['-assessed_on'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_fa', models.CharField(max_length=100, verbose_name='name (Persian)')),
                ('name_de', models.CharField(blank=True, max_length=100, verbose_name='name (German)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='name (English)')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='icon')),
                ('color', models.CharField(blank=True, default='#2F4F7F', max_length=7, verbose_name='colour')),
                ('category', models.CharField(choices=[('body', 'Body'), ('mind', 'Mind'), ('material', 'Practical / material'), ('social', 'Social')], default='mind', max_length=10, verbose_name='category')),
                ('cadence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='quarterly', max_length=10, verbose_name='cadence')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('importance', models.PositiveSmallIntegerField(blank=True, help_text="Optional 0-10. Separates 'this is low and it matters' from 'this is low and I do not mind'.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='importance')),
                ('definition', models.TextField(blank=True, help_text='What 0, 5 and 10 mean to you here. Writing this down keeps the scale stable over time instead of drifting with your mood.', verbose_name='definition')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='workspaces.workspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'domain',
                'verbose_name_plural': 'domains',
                'ordering': ['sort_order', 'name_fa'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveSmallIntegerField(help_text='0 = very weak, 10 = excellent.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='score')),
                ('target_value', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='target')),
                ('note', models.CharField(blank=True, help_text='One line on why. Turns a number back into a reason later.', max_length=300, verbose_name='note')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tracking.assessment', verbose_name='assessment')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='tracking.domain', verbose_name='domain')),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'scores',
                'ordering': ['domain__sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['workspace', '-assessed_on'], name='tracking_as_workspa_810231_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'assessed_on', 'cadence'), name='unique_live_assessment_per_date_and_cadence'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(fields=('workspace', 'name_fa'), name='unique_domain_name_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('assessment', 'domain'), name='one_score_per_domain_per_assessment'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0), ('value__lte', 10)), name='score_value_between_0_and_10'),
        ),
    ]
